// next/components/contact-form.tsx
"use client";

import { useState, type FormEvent } from "react";
import { useLocale, useTranslations } from "next-intl";
import { CircleAlert, CircleCheck } from "lucide-react";
import { api } from "@/lib/api";
import { ApiError, apiErrorKey } from "@/lib/api-error";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";

interface ContactFields {
  name: string;
  email: string;
  company: string;
  message: string;
  consent: boolean;
  website: string;
}

const EMPTY: ContactFields = {
  name: "",
  email: "",
  company: "",
  message: "",
  consent: false,
  website: "",
};

const EMAIL_PATTERN = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;

/**
 * Contact form (contract §4.8). Every submission carries the active `locale`,
 * a hidden honeypot (`website`) and a `consent` flag. Field-level validation is
 * client-side; backend `10001` shows a generic validation message and `42901`
 * (and any other code) is mapped through `apiErrorKey`.
 */
export function ContactForm() {
  const t = useTranslations("contact");
  const tRoot = useTranslations();
  const locale = useLocale();

  const [form, setForm] = useState<ContactFields>(EMPTY);
  const [errors, setErrors] = useState<Record<string, string>>({});
  const [submitting, setSubmitting] = useState(false);
  const [submitted, setSubmitted] = useState(false);
  const [formError, setFormError] = useState("");

  function update<K extends keyof ContactFields>(
    key: K,
    value: ContactFields[K],
  ) {
    setForm((prev) => ({ ...prev, [key]: value }));
  }

  function validate(): boolean {
    const next: Record<string, string> = {
      name: form.name.trim() ? "" : t("errors.nameRequired"),
      email: !form.email.trim()
        ? t("errors.emailRequired")
        : EMAIL_PATTERN.test(form.email.trim())
          ? ""
          : t("errors.emailInvalid"),
      message: form.message.trim() ? "" : t("errors.messageRequired"),
      consent: form.consent ? "" : t("errors.consentRequired"),
    };
    setErrors(next);
    return !Object.values(next).some(Boolean);
  }

  async function handleSubmit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    setFormError("");
    if (!validate()) {
      return;
    }
    setSubmitting(true);
    try {
      await api.post("/v1/public/contact", {
        name: form.name.trim(),
        email: form.email.trim(),
        company: form.company.trim(),
        message: form.message.trim(),
        locale,
        consent: form.consent,
        website: form.website,
      });
      setForm(EMPTY);
      setErrors({});
      setSubmitted(true);
    } catch (error) {
      setFormError(
        error instanceof ApiError
          ? error.code === 10001
            ? t("errors.validation")
            : tRoot(apiErrorKey(error.code))
          : tRoot("errorCodes.unknown"),
      );
    } finally {
      setSubmitting(false);
    }
  }

  if (submitted) {
    return (
      <div className="flex flex-col gap-3 rounded-xl border bg-card p-6">
        <div className="flex items-center gap-2">
          <CircleCheck className="size-5 text-primary" aria-hidden="true" />
          <p className="font-heading font-semibold">{t("successTitle")}</p>
        </div>
        <p className="text-sm text-muted-foreground">
          {t("successDescription")}
        </p>
        <Button
          type="button"
          variant="outline"
          className="self-start"
          onClick={() => {
            setSubmitted(false);
            setFormError("");
          }}
        >
          {t("sendAnother")}
        </Button>
      </div>
    );
  }

  return (
    <form className="flex flex-col gap-5" noValidate onSubmit={handleSubmit}>
      {formError ? (
        <div className="flex items-start gap-2 rounded-lg border border-destructive/40 bg-destructive/10 px-4 py-3 text-sm text-destructive">
          <CircleAlert className="mt-0.5 size-4 shrink-0" aria-hidden="true" />
          <p>{formError}</p>
        </div>
      ) : null}

      {/* Honeypot: rendered and hidden off-screen (not display:none) so bots fill it. */}
      <div
        className="absolute -left-[9999px] top-auto h-px w-px overflow-hidden"
        aria-hidden="true"
      >
        <label htmlFor="contact-website">Website</label>
        <input
          id="contact-website"
          name="website"
          type="text"
          tabIndex={-1}
          autoComplete="off"
          value={form.website}
          onChange={(event) => update("website", event.target.value)}
        />
      </div>

      <div className="grid gap-5 sm:grid-cols-2">
        <div className="flex flex-col gap-2">
          <Label htmlFor="contact-name">{t("fields.name")}</Label>
          <Input
            id="contact-name"
            name="name"
            autoComplete="name"
            aria-invalid={Boolean(errors.name)}
            value={form.name}
            onChange={(event) => update("name", event.target.value)}
          />
          {errors.name ? (
            <p className="text-xs text-destructive">{errors.name}</p>
          ) : null}
        </div>

        <div className="flex flex-col gap-2">
          <Label htmlFor="contact-email">{t("fields.email")}</Label>
          <Input
            id="contact-email"
            name="email"
            type="email"
            autoComplete="email"
            aria-invalid={Boolean(errors.email)}
            value={form.email}
            onChange={(event) => update("email", event.target.value)}
          />
          {errors.email ? (
            <p className="text-xs text-destructive">{errors.email}</p>
          ) : null}
        </div>
      </div>

      <div className="flex flex-col gap-2">
        <Label htmlFor="contact-company">{t("fields.company")}</Label>
        <Input
          id="contact-company"
          name="company"
          autoComplete="organization"
          value={form.company}
          onChange={(event) => update("company", event.target.value)}
        />
      </div>

      <div className="flex flex-col gap-2">
        <Label htmlFor="contact-message">{t("fields.message")}</Label>
        <Textarea
          id="contact-message"
          name="message"
          rows={5}
          aria-invalid={Boolean(errors.message)}
          value={form.message}
          onChange={(event) => update("message", event.target.value)}
        />
        {errors.message ? (
          <p className="text-xs text-destructive">{errors.message}</p>
        ) : null}
      </div>

      <div className="flex flex-col gap-2">
        <div className="flex items-start gap-2">
          <input
            id="contact-consent"
            name="consent"
            type="checkbox"
            className="mt-0.5 size-4 rounded border-input accent-primary"
            checked={form.consent}
            onChange={(event) => update("consent", event.target.checked)}
          />
          <Label htmlFor="contact-consent" className="font-normal">
            {t("fields.consent")}
          </Label>
        </div>
        {errors.consent ? (
          <p className="text-xs text-destructive">{errors.consent}</p>
        ) : null}
      </div>

      <Button type="submit" size="lg" className="self-start" disabled={submitting}>
        {t("submit")}
      </Button>
    </form>
  );
}

// frontend/app/components/ContactForm.vue
<script setup lang="ts">
const { t, locale } = useI18n()
const api = useApi()

const form = reactive({
  name: '',
  email: '',
  company: '',
  message: '',
  consent: false,
  website: ''
})

const errors = reactive<Record<string, string>>({})
const submitting = ref(false)
const submitted = ref(false)
const formError = ref('')

const EMAIL_PATTERN = /^[^\s@]+@[^\s@]+\.[^\s@]+$/

function validate(): boolean {
  errors.name = form.name.trim() ? '' : t('contact.errors.nameRequired')
  errors.email = !form.email.trim()
    ? t('contact.errors.emailRequired')
    : (EMAIL_PATTERN.test(form.email.trim()) ? '' : t('contact.errors.emailInvalid'))
  errors.message = form.message.trim() ? '' : t('contact.errors.messageRequired')
  errors.consent = form.consent ? '' : t('contact.errors.consentRequired')
  return !Object.values(errors).some(Boolean)
}

function reset() {
  form.name = ''
  form.email = ''
  form.company = ''
  form.message = ''
  form.consent = false
  form.website = ''
  Object.keys(errors).forEach((key) => {
    errors[key] = ''
  })
}

async function submit() {
  formError.value = ''
  if (!validate()) {
    return
  }
  submitting.value = true
  try {
    await api.post('/v1/public/contact', {
      name: form.name.trim(),
      email: form.email.trim(),
      company: form.company.trim(),
      message: form.message.trim(),
      locale: locale.value,
      consent: form.consent,
      website: form.website
    })
    reset()
    submitted.value = true
  } catch (error) {
    formError.value = error instanceof ApiError
      ? (error.code === 10001 ? t('contact.errors.validation') : t(apiErrorKey(error.code)))
      : t('errorCodes.unknown')
  } finally {
    submitting.value = false
  }
}

function submitAnother() {
  submitted.value = false
  formError.value = ''
}
</script>

<template>
  <div>
    <UAlert
      v-if="submitted"
      color="success"
      variant="soft"
      icon="i-lucide-circle-check"
      :title="t('contact.successTitle')"
      :description="t('contact.successDescription')"
    >
      <template #actions>
        <UButton
          color="neutral"
          variant="outline"
          @click="submitAnother"
        >
          {{ t('contact.sendAnother') }}
        </UButton>
      </template>
    </UAlert>

    <form
      v-else
      class="flex flex-col gap-5"
      novalidate
      @submit.prevent="submit"
    >
      <UAlert
        v-if="formError"
        color="error"
        variant="soft"
        icon="i-lucide-triangle-alert"
        :description="formError"
      />

      <!-- Honeypot: rendered and hidden off-screen (not display:none) so bots fill it. -->
      <div
        class="absolute -left-[9999px] top-auto h-px w-px overflow-hidden"
        aria-hidden="true"
      >
        <label for="contact-website">Website</label>
        <input
          id="contact-website"
          v-model="form.website"
          type="text"
          tabindex="-1"
          autocomplete="off"
          name="website"
        >
      </div>

      <div class="grid gap-5 sm:grid-cols-2">
        <UFormField
          :label="t('contact.fields.name')"
          :error="errors.name"
          required
        >
          <UInput
            v-model="form.name"
            class="w-full"
            autocomplete="name"
          />
        </UFormField>
        <UFormField
          :label="t('contact.fields.email')"
          :error="errors.email"
          required
        >
          <UInput
            v-model="form.email"
            type="email"
            class="w-full"
            autocomplete="email"
          />
        </UFormField>
      </div>

      <UFormField :label="t('contact.fields.company')">
        <UInput
          v-model="form.company"
          class="w-full"
          autocomplete="organization"
        />
      </UFormField>

      <UFormField
        :label="t('contact.fields.message')"
        :error="errors.message"
        required
      >
        <UTextarea
          v-model="form.message"
          class="w-full"
          :rows="5"
        />
      </UFormField>

      <UFormField :error="errors.consent">
        <UCheckbox
          v-model="form.consent"
          :label="t('contact.fields.consent')"
        />
      </UFormField>

      <UButton
        type="submit"
        size="lg"
        :loading="submitting"
        :disabled="submitting"
        class="self-start"
      >
        {{ t('contact.submit') }}
      </UButton>
    </form>
  </div>
</template>
