// next/components/markdown-content.tsx
import { cn } from "cn";
import { renderMarkdown } from "@/lib/markdown";

/**
 * Renders backend `body_md`. The Markdown is parsed and sanitised by
 * `renderMarkdown` before it reaches `dangerouslySetInnerHTML`; raw HTML is
 * never rendered directly (contract §7.5).
 */
export function MarkdownContent({
  content = "",
  className,
}: {
  content?: string;
  className?: string;
}) {
  const { html } = renderMarkdown(content);
  if (!html) {
    return null;
  }

  return (
    <div
      className={cn(
        "text-sm leading-7 break-words",
        "[&>*:first-child]:mt-0",
        "[&_h1]:mt-6 [&_h1]:mb-3 [&_h1]:scroll-mt-20 [&_h1]:text-2xl [&_h1]:font-semibold",
        "[&_h2]:mt-6 [&_h2]:mb-3 [&_h2]:scroll-mt-20 [&_h2]:text-xl [&_h2]:font-semibold",
        "[&_h3]:mt-5 [&_h3]:mb-2 [&_h3]:scroll-mt-20 [&_h3]:text-lg [&_h3]:font-semibold",
        "[&_h4]:mt-4 [&_h4]:mb-2 [&_h4]:scroll-mt-20 [&_h4]:font-semibold",
        "[&_p]:my-3 [&_ul]:my-3 [&_ul]:list-disc [&_ul]:pl-6",
        "[&_ol]:my-3 [&_ol]:list-decimal [&_ol]:pl-6 [&_li]:my-1",
        "[&_a]:text-primary [&_a]:underline [&_a]:underline-offset-2",
        "[&_blockquote]:my-3 [&_blockquote]:border-l-2 [&_blockquote]:border-border [&_blockquote]:pl-4 [&_blockquote]:text-muted-foreground",
        "[&_code]:rounded [&_code]:bg-muted [&_code]:px-1 [&_code]:py-0.5 [&_code]:text-[0.85em]",
        "[&_pre]:my-3 [&_pre]:overflow-x-auto [&_pre]:rounded-lg [&_pre]:border [&_pre]:bg-muted [&_pre]:p-4",
        "[&_pre_code]:bg-transparent [&_pre_code]:p-0",
        "[&_hr]:my-6 [&_hr]:border-border",
        "[&_img]:my-3 [&_img]:max-w-full [&_img]:rounded-lg",
        "[&_table]:my-3 [&_table]:block [&_table]:w-full [&_table]:overflow-x-auto [&_table]:border-collapse",
        "[&_th]:border [&_th]:border-border [&_th]:px-3 [&_th]:py-2 [&_th]:text-left",
        "[&_td]:border [&_td]:border-border [&_td]:px-3 [&_td]:py-2 [&_td]:text-left",
        className,
      )}
      dangerouslySetInnerHTML={{ __html: html }}
    />
  );
}

// frontend/app/components/MarkdownContent.vue
<script setup lang="ts">
const props = withDefaults(defineProps<{
  content?: string
}>(), {
  content: ''
})

// `body_md` is parsed and sanitised by `renderMarkdown` before it reaches
// `v-html`; raw HTML is never rendered directly (contract §7.5).
const html = computed(() => renderMarkdown(props.content).html)
</script>

<template>
  <!-- eslint-disable vue/no-v-html -- `html` is sanitised by renderMarkdown -->
  <div
    class="markdown"
    v-html="html"
  />
  <!-- eslint-enable vue/no-v-html -->
</template>

<style scoped>
.markdown {
  color: var(--ui-text);
  line-height: 1.75;
  word-break: break-word;
}

.markdown :deep(> :first-child) {
  margin-top: 0;
}

.markdown :deep(h1),
.markdown :deep(h2),
.markdown :deep(h3),
.markdown :deep(h4) {
  color: var(--ui-text-highlighted);
  font-weight: 600;
  line-height: 1.3;
  margin: 1.75em 0 0.75em;
  scroll-margin-top: 5rem;
}

.markdown :deep(h1) { font-size: 1.75rem; }
.markdown :deep(h2) { font-size: 1.4rem; }
.markdown :deep(h3) { font-size: 1.15rem; }
.markdown :deep(h4) { font-size: 1rem; }

.markdown :deep(p),
.markdown :deep(ul),
.markdown :deep(ol),
.markdown :deep(blockquote),
.markdown :deep(pre),
.markdown :deep(table) {
  margin: 0.85em 0;
}

.markdown :deep(ul),
.markdown :deep(ol) {
  padding-left: 1.4em;
}

.markdown :deep(ul) { list-style: disc; }
.markdown :deep(ol) { list-style: decimal; }
.markdown :deep(li) { margin: 0.25em 0; }

.markdown :deep(a) {
  color: var(--ui-primary);
  text-decoration: underline;
  text-underline-offset: 2px;
}

.markdown :deep(blockquote) {
  border-left: 3px solid var(--ui-border);
  color: var(--ui-text-muted);
  padding-left: 1em;
}

.markdown :deep(code) {
  background: var(--ui-bg-muted);
  border-radius: 0.25rem;
  font-size: 0.875em;
  padding: 0.15em 0.4em;
}

.markdown :deep(pre) {
  background: var(--ui-bg-muted);
  border: 1px solid var(--ui-border);
  border-radius: 0.5rem;
  overflow-x: auto;
  padding: 1em;
}

.markdown :deep(pre code) {
  background: transparent;
  padding: 0;
}

.markdown :deep(hr) {
  border: 0;
  border-top: 1px solid var(--ui-border);
  margin: 2em 0;
}

.markdown :deep(img) {
  border-radius: 0.5rem;
  max-width: 100%;
}

.markdown :deep(table) {
  border-collapse: collapse;
  display: block;
  overflow-x: auto;
  width: 100%;
}

.markdown :deep(th),
.markdown :deep(td) {
  border: 1px solid var(--ui-border);
  padding: 0.5em 0.75em;
  text-align: left;
}
</style>
