// frontend/app/pages/account/security.vue
<script setup lang="ts">
definePageMeta({ layout: 'account', middleware: 'auth' })

const { t } = useI18n()
const router = useRouter()
const { changePassword } = useAuth()

const form = reactive({
  current: '',
  next: '',
  confirm: ''
})
const errors = reactive<Record<string, string>>({})
const formError = ref('')
const submitting = ref(false)

function byteLength(value: string): number {
  return new TextEncoder().encode(value).length
}

function validate(): boolean {
  errors.current = form.current ? '' : t('account.security.errors.currentRequired')
  const nextBytes = byteLength(form.next)
  errors.next = !form.next
    ? t('account.security.errors.newRequired')
    : (nextBytes < 8 || nextBytes > 72 ? t('account.security.errors.newLength') : '')
  errors.confirm = !form.confirm
    ? t('account.security.errors.confirmRequired')
    : (form.confirm === form.next ? '' : t('account.security.errors.confirmMismatch'))
  return !Object.values(errors).some(Boolean)
}

async function submit() {
  formError.value = ''
  if (!validate()) {
    return
  }
  submitting.value = true
  try {
    await changePassword(form.current, form.next)
    await router.push({ path: '/login', query: { changed: '1' } })
  } catch (error) {
    if (error instanceof ApiError && error.code === 40005) {
      errors.current = t('errorCodes.40005')
    } else {
      formError.value = error instanceof ApiError ? t(apiErrorKey(error.code)) : t('errorCodes.unknown')
    }
  } finally {
    submitting.value = false
  }
}

useSeo({ title: t('account.security.title') })
</script>

<template>
  <div>
    <UPageHeader
      :title="t('account.security.title')"
      :description="t('account.security.subtitle')"
    />

    <form
      class="mt-8 flex max-w-md flex-col gap-5"
      novalidate
      @submit.prevent="submit"
    >
      <UAlert
        v-if="formError"
        color="error"
        variant="soft"
        icon="i-lucide-triangle-alert"
        :description="formError"
      />

      <UFormField
        :label="t('account.security.currentPassword')"
        :error="errors.current"
        required
      >
        <UInput
          v-model="form.current"
          type="password"
          class="w-full"
          autocomplete="current-password"
        />
      </UFormField>

      <UFormField
        :label="t('account.security.newPassword')"
        :error="errors.next"
        :hint="t('account.security.passwordHint')"
        required
      >
        <UInput
          v-model="form.next"
          type="password"
          class="w-full"
          autocomplete="new-password"
        />
      </UFormField>

      <UFormField
        :label="t('account.security.confirmPassword')"
        :error="errors.confirm"
        required
      >
        <UInput
          v-model="form.confirm"
          type="password"
          class="w-full"
          autocomplete="new-password"
        />
      </UFormField>

      <UButton
        type="submit"
        size="lg"
        :loading="submitting"
        :disabled="submitting"
        class="self-start"
      >
        {{ t('account.security.submit') }}
      </UButton>
    </form>
  </div>
</template>

// next/app/[locale]/account/security/page.tsx
"use client";

import { useState } from "react";
import { useTranslations } from "next-intl";
import { useRouter } from "@/i18n/navigation";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { useAuth } from "@/lib/auth";
import { ApiError, apiErrorKey } from "@/lib/api-error";
import { byteLength } from "@/lib/format";
import { FormAlert } from "@/components/auth/form-alert";
import { FormField } from "@/components/auth/form-field";

export default function AccountSecurityPage() {
  const t = useTranslations();
  const router = useRouter();
  const { changePassword } = useAuth();

  const [current, setCurrent] = useState("");
  const [next, setNext] = useState("");
  const [confirm, setConfirm] = useState("");
  const [fieldErrors, setFieldErrors] = useState<{
    current?: string;
    next?: string;
    confirm?: string;
  }>({});
  const [formError, setFormError] = useState("");
  const [submitting, setSubmitting] = useState(false);

  function validate(): boolean {
    const errors: typeof fieldErrors = {};
    if (!current) {
      errors.current = t("account.security.errors.currentRequired");
    }
    const nextBytes = byteLength(next);
    if (!next) {
      errors.next = t("account.security.errors.newRequired");
    } else if (nextBytes < 8 || nextBytes > 72) {
      errors.next = t("account.security.errors.newLength");
    }
    if (!confirm) {
      errors.confirm = t("account.security.errors.confirmRequired");
    } else if (confirm !== next) {
      errors.confirm = t("account.security.errors.confirmMismatch");
    }
    setFieldErrors(errors);
    return Object.keys(errors).length === 0;
  }

  async function submit(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault();
    setFormError("");
    if (!validate()) {
      return;
    }
    setSubmitting(true);
    try {
      await changePassword(current, next);
      router.push({ pathname: "/login", query: { changed: "1" } });
    } catch (error) {
      if (error instanceof ApiError && error.code === 40005) {
        setFieldErrors((previous) => ({
          ...previous,
          current: t("errorCodes.40005"),
        }));
      } else {
        setFormError(
          error instanceof ApiError
            ? t(apiErrorKey(error.code))
            : t("errorCodes.unknown"),
        );
      }
    } finally {
      setSubmitting(false);
    }
  }

  return (
    <div>
      <header>
        <h1 className="font-heading text-2xl font-semibold tracking-tight">
          {t("account.security.title")}
        </h1>
        <p className="mt-1 text-muted-foreground">
          {t("account.security.subtitle")}
        </p>
      </header>

      <form
        className="mt-8 flex max-w-md flex-col gap-5"
        noValidate
        onSubmit={submit}
      >
        {formError ? <FormAlert description={formError} /> : null}

        <FormField
          label={t("account.security.currentPassword")}
          htmlFor="security-current"
          error={fieldErrors.current}
        >
          <Input
            id="security-current"
            type="password"
            autoComplete="current-password"
            value={current}
            onChange={(event) => setCurrent(event.target.value)}
          />
        </FormField>

        <FormField
          label={t("account.security.newPassword")}
          htmlFor="security-next"
          hint={t("account.security.passwordHint")}
          error={fieldErrors.next}
        >
          <Input
            id="security-next"
            type="password"
            autoComplete="new-password"
            value={next}
            onChange={(event) => setNext(event.target.value)}
          />
        </FormField>

        <FormField
          label={t("account.security.confirmPassword")}
          htmlFor="security-confirm"
          error={fieldErrors.confirm}
        >
          <Input
            id="security-confirm"
            type="password"
            autoComplete="new-password"
            value={confirm}
            onChange={(event) => setConfirm(event.target.value)}
          />
        </FormField>

        <Button
          type="submit"
          size="lg"
          className="self-start"
          disabled={submitting}
        >
          {t("account.security.submit")}
        </Button>
      </form>
    </div>
  );
}
