// frontend/app/pages/account/profile.vue
<script setup lang="ts">
import type { UpdateProfilePayload } from '~/composables/useAuth'

definePageMeta({ layout: 'account', middleware: 'auth' })

const { t } = useI18n()
const { user, updateProfile } = useAuth()

const form = reactive({
  nickname: user.value?.nickname || '',
  avatar_url: user.value?.avatar_url || ''
})
const formError = ref('')
const saved = ref(false)
const submitting = ref(false)

async function submit() {
  formError.value = ''
  saved.value = false

  const payload: UpdateProfilePayload = {}
  if (form.nickname.trim() !== (user.value?.nickname || '')) {
    payload.nickname = form.nickname.trim()
  }
  if (form.avatar_url.trim() !== (user.value?.avatar_url || '')) {
    payload.avatar_url = form.avatar_url.trim()
  }
  if (!Object.keys(payload).length) {
    saved.value = true
    return
  }

  submitting.value = true
  try {
    const updated = await updateProfile(payload)
    form.nickname = updated.nickname
    form.avatar_url = updated.avatar_url
    saved.value = true
  } catch (error) {
    formError.value = error instanceof ApiError ? t(apiErrorKey(error.code)) : t('errorCodes.unknown')
  } finally {
    submitting.value = false
  }
}

useSeo({ title: t('account.profile.title') })
</script>

<template>
  <div>
    <UPageHeader
      :title="t('account.profile.title')"
      :description="t('account.profile.subtitle')"
    />

    <form
      class="mt-8 flex max-w-md flex-col gap-5"
      novalidate
      @submit.prevent="submit"
    >
      <UAlert
        v-if="saved"
        color="success"
        variant="soft"
        icon="i-lucide-circle-check"
        :description="t('account.profile.saved')"
      />

      <UAlert
        v-if="formError"
        color="error"
        variant="soft"
        icon="i-lucide-triangle-alert"
        :description="formError"
      />

      <UFormField
        :label="t('account.profile.nickname')"
        :hint="t('account.profile.nicknameHint')"
      >
        <UInput
          v-model="form.nickname"
          class="w-full"
          autocomplete="nickname"
        />
      </UFormField>

      <UFormField :label="t('account.profile.avatarUrl')">
        <UInput
          v-model="form.avatar_url"
          class="w-full"
          placeholder="https://…"
        />
      </UFormField>

      <UButton
        type="submit"
        size="lg"
        :loading="submitting"
        :disabled="submitting"
        class="self-start"
      >
        {{ t('account.profile.submit') }}
      </UButton>
    </form>
  </div>
</template>

// next/app/[locale]/account/profile/page.tsx
"use client";

import { useState } from "react";
import { useTranslations } from "next-intl";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { useAuth, type UpdateProfilePayload } from "@/lib/auth";
import { ApiError, apiErrorKey } from "@/lib/api-error";
import { FormAlert } from "@/components/auth/form-alert";
import { FormField } from "@/components/auth/form-field";

export default function AccountProfilePage() {
  const t = useTranslations();
  const { user, updateProfile } = useAuth();

  const [nickname, setNickname] = useState(user?.nickname ?? "");
  const [avatarUrl, setAvatarUrl] = useState(user?.avatar_url ?? "");
  const [formError, setFormError] = useState("");
  const [saved, setSaved] = useState(false);
  const [submitting, setSubmitting] = useState(false);

  if (!user) {
    return null;
  }

  async function submit(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault();
    if (!user) {
      return;
    }
    setFormError("");
    setSaved(false);

    const payload: UpdateProfilePayload = {};
    if (nickname.trim() !== user.nickname) {
      payload.nickname = nickname.trim();
    }
    if (avatarUrl.trim() !== user.avatar_url) {
      payload.avatar_url = avatarUrl.trim();
    }
    if (Object.keys(payload).length === 0) {
      setSaved(true);
      return;
    }

    setSubmitting(true);
    try {
      const updated = await updateProfile(payload);
      setNickname(updated.nickname);
      setAvatarUrl(updated.avatar_url);
      setSaved(true);
    } catch (error) {
      setFormError(
        error instanceof ApiError
          ? t(apiErrorKey(error.code))
          : t("errorCodes.unknown"),
      );
    } finally {
      setSubmitting(false);
    }
  }

  return (
    <div>
      <header>
        <h1 className="font-heading text-2xl font-semibold tracking-tight">
          {t("account.profile.title")}
        </h1>
        <p className="mt-1 text-muted-foreground">
          {t("account.profile.subtitle")}
        </p>
      </header>

      <form
        className="mt-8 flex max-w-md flex-col gap-5"
        noValidate
        onSubmit={submit}
      >
        {saved ? (
          <FormAlert tone="success" description={t("account.profile.saved")} />
        ) : null}
        {formError ? <FormAlert description={formError} /> : null}

        <FormField
          label={t("account.profile.nickname")}
          htmlFor="profile-nickname"
          hint={t("account.profile.nicknameHint")}
        >
          <Input
            id="profile-nickname"
            autoComplete="nickname"
            value={nickname}
            onChange={(event) => setNickname(event.target.value)}
          />
        </FormField>

        <FormField
          label={t("account.profile.avatarUrl")}
          htmlFor="profile-avatar"
        >
          <Input
            id="profile-avatar"
            placeholder="https://…"
            value={avatarUrl}
            onChange={(event) => setAvatarUrl(event.target.value)}
          />
        </FormField>

        <Button
          type="submit"
          size="lg"
          className="self-start"
          disabled={submitting}
        >
          {t("account.profile.submit")}
        </Button>
      </form>
    </div>
  );
}
