// frontend/app/pages/account/points.vue
<script setup lang="ts">
import type { PointTransactionPage } from '~/composables/useAuth'

definePageMeta({ layout: 'account', middleware: 'auth' })

const { t, locale } = useI18n()
const { user } = useAuth()
const api = useApi()

const page = ref(1)
const pageSize = 20
const data = ref<PointTransactionPage | null>(null)
const pending = ref(true)
const error = ref<unknown>(null)

/** Format a fixed-point decimal string with 4 fraction digits, never via float. */
function formatPoints(raw: string): string {
  const value = (raw || '').trim()
  const negative = value.startsWith('-')
  const unsigned = negative ? value.slice(1) : value
  const [intRaw = '0', fracRaw = ''] = unsigned.split('.')
  const intPart = intRaw.replace(/^0+(?=\d)/, '') || '0'
  let frac = fracRaw.replace(/\D.*$/, '')
  frac = frac.length >= 4 ? frac.slice(0, 4) : frac.padEnd(4, '0')
  return `${negative ? '-' : ''}${intPart}.${frac}`
}

function formatDateTime(value: string): string {
  if (!value) {
    return '—'
  }
  const date = new Date(value)
  if (Number.isNaN(date.getTime())) {
    return value
  }
  return new Intl.DateTimeFormat(locale.value, { dateStyle: 'medium', timeStyle: 'short' }).format(date)
}

function deltaClass(delta: string): string {
  const value = (delta || '').trim()
  if (value.startsWith('-')) {
    return 'text-error'
  }
  if (/^0*(\.0*)?$/.test(value.replace(/^\+/, ''))) {
    return 'text-muted'
  }
  return 'text-success'
}

async function load() {
  pending.value = true
  error.value = null
  try {
    data.value = await api.get<PointTransactionPage>('/v1/me/point-transactions', {
      query: { page: page.value, page_size: pageSize }
    })
  } catch (err) {
    error.value = err
  } finally {
    pending.value = false
  }
}

const totalPages = computed(() => {
  if (!data.value) {
    return 1
  }
  return Math.max(1, Math.ceil(data.value.total / (data.value.page_size || pageSize)))
})

function changePage(next: number) {
  if (next < 1 || next > totalPages.value || next === page.value) {
    return
  }
  page.value = next
}

watch(page, load)
onMounted(load)

useSeo({ title: t('account.points.title') })
</script>

<template>
  <div>
    <UPageHeader
      :title="t('account.points.title')"
      :description="t('account.points.subtitle')"
    />

    <div
      v-if="user"
      class="mt-8 grid gap-4 sm:grid-cols-3"
    >
      <div class="rounded-lg border border-default p-4">
        <p class="text-sm text-muted">
          {{ t('account.points.balance') }}
        </p>
        <p class="mt-1 font-mono text-2xl font-semibold text-highlighted">
          {{ formatPoints(user.points_balance) }}
        </p>
      </div>
      <div class="rounded-lg border border-default p-4">
        <p class="text-sm text-muted">
          {{ t('account.points.consumption') }}
        </p>
        <p class="mt-1 font-mono text-2xl font-semibold text-highlighted">
          {{ formatPoints(user.consumption_points) }}
        </p>
      </div>
      <div class="rounded-lg border border-default p-4">
        <p class="text-sm text-muted">
          {{ t('account.points.level') }}
        </p>
        <p class="mt-1 text-2xl font-semibold text-highlighted">
          {{ user.level?.name || t('account.overview.noLevel') }}
        </p>
      </div>
    </div>

    <div class="mt-8">
      <AppLoading v-if="pending" />
      <AppErrorState
        v-else-if="error"
        :error="error"
        @retry="load"
      />
      <AppEmptyState
        v-else-if="!data?.items.length"
        :description="t('account.points.empty')"
        icon="i-lucide-coins"
      />
      <div
        v-else
        class="overflow-x-auto rounded-lg border border-default"
      >
        <table class="w-full text-left text-sm">
          <thead class="bg-elevated/50 text-muted">
            <tr>
              <th class="px-4 py-3 font-medium">
                {{ t('account.points.table.time') }}
              </th>
              <th class="px-4 py-3 font-medium">
                {{ t('account.points.table.reason') }}
              </th>
              <th class="px-4 py-3 text-right font-medium">
                {{ t('account.points.table.change') }}
              </th>
              <th class="px-4 py-3 text-right font-medium">
                {{ t('account.points.table.balance') }}
              </th>
              <th class="px-4 py-3 text-right font-medium">
                {{ t('account.points.table.consumptionChange') }}
              </th>
            </tr>
          </thead>
          <tbody>
            <tr
              v-for="item in data.items"
              :key="item.id"
              class="border-t border-default"
            >
              <td class="whitespace-nowrap px-4 py-3 text-muted">
                {{ formatDateTime(item.created_at) }}
              </td>
              <td class="px-4 py-3">
                {{ item.reason || '—' }}
              </td>
              <td
                class="px-4 py-3 text-right font-mono"
                :class="deltaClass(item.points_delta)"
              >
                {{ formatPoints(item.points_delta) }}
              </td>
              <td class="px-4 py-3 text-right font-mono">
                {{ formatPoints(item.balance_after) }}
              </td>
              <td class="px-4 py-3 text-right font-mono text-muted">
                {{ formatPoints(item.consumption_delta) }}
              </td>
            </tr>
          </tbody>
        </table>
      </div>

      <div
        v-if="data && data.total > 0"
        class="mt-4 flex items-center justify-between"
      >
        <p class="text-sm text-muted">
          {{ t('account.points.pageInfo', { page: data.page, total: totalPages }) }}
        </p>
        <div class="flex gap-2">
          <UButton
            color="neutral"
            variant="outline"
            size="sm"
            icon="i-lucide-chevron-left"
            :disabled="page <= 1"
            @click="changePage(page - 1)"
          >
            {{ t('account.points.previous') }}
          </UButton>
          <UButton
            color="neutral"
            variant="outline"
            size="sm"
            trailing-icon="i-lucide-chevron-right"
            :disabled="page >= totalPages"
            @click="changePage(page + 1)"
          >
            {{ t('account.points.next') }}
          </UButton>
        </div>
      </div>
    </div>
  </div>
</template>

// next/app/[locale]/account/points/page.tsx
"use client";

import { useEffect, useState } from "react";
import { useLocale, useTranslations } from "next-intl";
import { CoinsIcon } from "lucide-react";
import { api } from "@/lib/api";
import { ApiError, apiErrorKey } from "@/lib/api-error";
import type { PointTransactionPage } from "@/lib/auth";
import { useAuth } from "@/lib/auth";
import { formatDateTime, formatPoints, isZeroPoints } from "@/lib/format";
import { AppLoading } from "@/components/app-loading";
import { Button } from "@/components/ui/button";
import { FormAlert } from "@/components/auth/form-alert";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";

const PAGE_SIZE = 20;

function deltaClass(delta: string): string {
  if (delta.trim().startsWith("-")) {
    return "text-destructive";
  }
  return isZeroPoints(delta) ? "text-muted-foreground" : "text-emerald-600 dark:text-emerald-400";
}

export default function AccountPointsPage() {
  const t = useTranslations();
  const locale = useLocale();
  const { user } = useAuth();

  const [page, setPage] = useState(1);
  const [reloadToken, setReloadToken] = useState(0);
  const [data, setData] = useState<PointTransactionPage | null>(null);
  const [pending, setPending] = useState(true);
  const [error, setError] = useState<unknown>(null);

  useEffect(() => {
    let active = true;
    (async () => {
      try {
        const result = await api.get<PointTransactionPage>(
          "/v1/me/point-transactions",
          { query: { page, page_size: PAGE_SIZE } },
        );
        if (active) {
          setData(result);
          setError(null);
        }
      } catch (err) {
        if (active) {
          setError(err);
        }
      } finally {
        if (active) {
          setPending(false);
        }
      }
    })();
    return () => {
      active = false;
    };
  }, [page, reloadToken]);

  function changePage(next: number) {
    setPending(true);
    setPage(next);
  }

  function reload() {
    setPending(true);
    setReloadToken((value) => value + 1);
  }

  const totalPages = data
    ? Math.max(1, Math.ceil(data.total / (data.page_size || PAGE_SIZE)))
    : 1;

  if (!user) {
    return null;
  }

  return (
    <div>
      <header>
        <h1 className="font-heading text-2xl font-semibold tracking-tight">
          {t("account.points.title")}
        </h1>
        <p className="mt-1 text-muted-foreground">
          {t("account.points.subtitle")}
        </p>
      </header>

      <div className="mt-8 grid gap-4 sm:grid-cols-3">
        <div className="rounded-lg border p-4">
          <p className="text-sm text-muted-foreground">
            {t("account.points.balance")}
          </p>
          <p className="mt-1 font-mono text-2xl font-semibold">
            {formatPoints(user.points_balance)}
          </p>
        </div>
        <div className="rounded-lg border p-4">
          <p className="text-sm text-muted-foreground">
            {t("account.points.consumption")}
          </p>
          <p className="mt-1 font-mono text-2xl font-semibold">
            {formatPoints(user.consumption_points)}
          </p>
        </div>
        <div className="rounded-lg border p-4">
          <p className="text-sm text-muted-foreground">
            {t("account.points.level")}
          </p>
          <p className="mt-1 text-2xl font-semibold">
            {user.level?.name || t("account.overview.noLevel")}
          </p>
        </div>
      </div>

      <div className="mt-8">
        {pending ? (
          <AppLoading />
        ) : error ? (
          <FormAlert
            description={
              error instanceof ApiError
                ? t(apiErrorKey(error.code))
                : t("errorCodes.unknown")
            }
            action={
              <Button type="button" variant="outline" onClick={reload}>
                {t("common.retry")}
              </Button>
            }
          />
        ) : !data?.items.length ? (
          <div className="flex flex-col items-center gap-2 rounded-lg border border-dashed py-12 text-muted-foreground">
            <CoinsIcon className="size-6" />
            <p className="text-sm">{t("account.points.empty")}</p>
          </div>
        ) : (
          <div className="overflow-hidden rounded-lg border">
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>{t("account.points.table.time")}</TableHead>
                  <TableHead>{t("account.points.table.reason")}</TableHead>
                  <TableHead className="text-right">
                    {t("account.points.table.change")}
                  </TableHead>
                  <TableHead className="text-right">
                    {t("account.points.table.balance")}
                  </TableHead>
                  <TableHead className="text-right">
                    {t("account.points.table.consumptionChange")}
                  </TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {data.items.map((item) => (
                  <TableRow key={item.id}>
                    <TableCell className="text-muted-foreground">
                      {formatDateTime(item.created_at, locale)}
                    </TableCell>
                    <TableCell>{item.reason || "—"}</TableCell>
                    <TableCell
                      className={`text-right font-mono ${deltaClass(item.points_delta)}`}
                    >
                      {formatPoints(item.points_delta)}
                    </TableCell>
                    <TableCell className="text-right font-mono">
                      {formatPoints(item.balance_after)}
                    </TableCell>
                    <TableCell className="text-right font-mono text-muted-foreground">
                      {formatPoints(item.consumption_delta)}
                    </TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          </div>
        )}

        {data && data.total > 0 ? (
          <div className="mt-4 flex items-center justify-between">
            <p className="text-sm text-muted-foreground">
              {t("account.points.pageInfo", { page: data.page, total: totalPages })}
            </p>
            <div className="flex gap-2">
              <Button
                type="button"
                variant="outline"
                size="sm"
                disabled={page <= 1}
                onClick={() => changePage(Math.max(1, page - 1))}
              >
                {t("account.points.previous")}
              </Button>
              <Button
                type="button"
                variant="outline"
                size="sm"
                disabled={page >= totalPages}
                onClick={() => changePage(Math.min(totalPages, page + 1))}
              >
                {t("account.points.next")}
              </Button>
            </div>
          </div>
        ) : null}
      </div>
    </div>
  );
}
