// frontend/app/pages/account/index.vue
<script setup lang="ts">
definePageMeta({ layout: 'account', middleware: 'auth' })

const { t, locale } = useI18n()
const { user } = useAuth()

/** Format a fixed-point decimal string with 4 fraction digits, never via float. */
function formatPoints(raw: string): string {
  const value = (raw || '').trim()
  const negative = value.startsWith('-')
  const unsigned = negative ? value.slice(1) : value
  const [intRaw = '0', fracRaw = ''] = unsigned.split('.')
  const intPart = intRaw.replace(/^0+(?=\d)/, '') || '0'
  let frac = fracRaw.replace(/\D.*$/, '')
  frac = frac.length >= 4 ? frac.slice(0, 4) : frac.padEnd(4, '0')
  return `${negative ? '-' : ''}${intPart}.${frac}`
}

function formatDateTime(value: string): string {
  if (!value) {
    return '—'
  }
  const date = new Date(value)
  if (Number.isNaN(date.getTime())) {
    return value
  }
  return new Intl.DateTimeFormat(locale.value, { dateStyle: 'medium', timeStyle: 'short' }).format(date)
}

useSeo({ title: t('account.overview.title') })
</script>

<template>
  <div v-if="user">
    <UPageHeader
      :title="t('account.overview.title')"
      :description="t('account.overview.subtitle')"
    />

    <div class="mt-8 flex items-center gap-4">
      <UAvatar
        :src="user.avatar_url || undefined"
        :alt="user.nickname || user.username"
        icon="i-lucide-user"
        size="xl"
      />
      <div>
        <p class="text-lg font-semibold text-highlighted">
          {{ user.nickname || user.username }}
        </p>
        <p class="text-sm text-muted">
          {{ user.email }}
        </p>
      </div>
    </div>

    <dl class="mt-8 grid gap-4 sm:grid-cols-2">
      <div class="rounded-lg border border-default p-4">
        <dt class="text-sm text-muted">
          {{ t('account.overview.username') }}
        </dt>
        <dd class="mt-1 font-medium text-highlighted">
          {{ user.username }}
        </dd>
      </div>
      <div class="rounded-lg border border-default p-4">
        <dt class="text-sm text-muted">
          {{ t('account.overview.email') }}
        </dt>
        <dd class="mt-1 flex items-center gap-2 font-medium text-highlighted">
          <span class="truncate">{{ user.email }}</span>
          <UBadge
            v-if="user.status === 'pending_verification'"
            color="warning"
            variant="soft"
            size="sm"
          >
            {{ t('account.overview.unverified') }}
          </UBadge>
        </dd>
      </div>
      <div class="rounded-lg border border-default p-4">
        <dt class="text-sm text-muted">
          {{ t('account.overview.level') }}
        </dt>
        <dd class="mt-1 font-medium text-highlighted">
          {{ user.level?.name || t('account.overview.noLevel') }}
        </dd>
      </div>
      <div class="rounded-lg border border-default p-4">
        <dt class="text-sm text-muted">
          {{ t('account.overview.joinedAt') }}
        </dt>
        <dd class="mt-1 font-medium text-highlighted">
          {{ formatDateTime(user.created_at) }}
        </dd>
      </div>
      <div class="rounded-lg border border-default p-4">
        <dt class="text-sm text-muted">
          {{ t('account.overview.pointsBalance') }}
        </dt>
        <dd class="mt-1 font-mono text-lg font-semibold text-highlighted">
          {{ formatPoints(user.points_balance) }}
        </dd>
      </div>
      <div class="rounded-lg border border-default p-4">
        <dt class="text-sm text-muted">
          {{ t('account.overview.consumption') }}
        </dt>
        <dd class="mt-1 font-mono text-lg font-semibold text-highlighted">
          {{ formatPoints(user.consumption_points) }}
        </dd>
      </div>
    </dl>
  </div>
</template>

// next/app/[locale]/account/page.tsx
"use client";

import { useLocale, useTranslations } from "next-intl";
import { useAuth } from "@/lib/auth";
import { formatDateTime, formatPoints } from "@/lib/format";
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";
import { Badge } from "@/components/ui/badge";

function DefinitionCard({
  label,
  children,
}: {
  label: string;
  children: React.ReactNode;
}) {
  return (
    <div className="rounded-lg border p-4">
      <dt className="text-sm text-muted-foreground">{label}</dt>
      <dd className="mt-1 font-medium">{children}</dd>
    </div>
  );
}

export default function AccountOverviewPage() {
  const t = useTranslations();
  const locale = useLocale();
  const { user } = useAuth();

  if (!user) {
    return null;
  }

  return (
    <div>
      <header>
        <h1 className="font-heading text-2xl font-semibold tracking-tight">
          {t("account.overview.title")}
        </h1>
        <p className="mt-1 text-muted-foreground">
          {t("account.overview.subtitle")}
        </p>
      </header>

      <div className="mt-8 flex items-center gap-4">
        <Avatar size="lg">
          {user.avatar_url ? (
            <AvatarImage src={user.avatar_url} alt={user.nickname || user.username} />
          ) : null}
          <AvatarFallback>{user.username.slice(0, 1).toUpperCase()}</AvatarFallback>
        </Avatar>
        <div>
          <p className="text-lg font-semibold">{user.nickname || user.username}</p>
          <p className="text-sm text-muted-foreground">{user.email}</p>
        </div>
      </div>

      <dl className="mt-8 grid gap-4 sm:grid-cols-2">
        <DefinitionCard label={t("account.overview.username")}>
          {user.username}
        </DefinitionCard>
        <DefinitionCard label={t("account.overview.email")}>
          <span className="flex items-center gap-2">
            <span className="truncate">{user.email}</span>
            {user.status === "pending_verification" ? (
              <Badge variant="outline">{t("account.overview.unverified")}</Badge>
            ) : null}
          </span>
        </DefinitionCard>
        <DefinitionCard label={t("account.overview.level")}>
          {user.level?.name || t("account.overview.noLevel")}
        </DefinitionCard>
        <DefinitionCard label={t("account.overview.joinedAt")}>
          {formatDateTime(user.created_at, locale)}
        </DefinitionCard>
        <DefinitionCard label={t("account.overview.pointsBalance")}>
          <span className="font-mono text-lg font-semibold">
            {formatPoints(user.points_balance)}
          </span>
        </DefinitionCard>
        <DefinitionCard label={t("account.overview.consumption")}>
          <span className="font-mono text-lg font-semibold">
            {formatPoints(user.consumption_points)}
          </span>
        </DefinitionCard>
      </dl>
    </div>
  );
}
